# Generated by Django 6.0 on 2025-12-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('org_type', models.CharField(blank=True, max_length=100)),
                ('estimated_users', models.PositiveIntegerField()),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_date_of_birth', models.DateField()),
                ('baridimob_transaction_ref', models.CharField(max_length=100)),
                ('baridimob_transaction_date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='org_requests/receipts/')),
                ('accept_terms', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
