# Generated by Django 6.0 on 2025-12-27 21:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(help_text='Exactly 10 digits.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Organization ID must be exactly 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.plan'),
        ),
    ]
