# Generated by Django 6.0 on 2025-12-27 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_organization_org_id_alter_organization_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(help_text='Exactly 10 digits.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_org_id', message='Organization ID must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
