# Generated by Django 6.0.2 on 2026-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in months (e.g. 1, 2, 6, 12)', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
