# Generated by Django 6.0 on 2025-12-28 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_activitylog_accesscontrolentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='pin_code',
            field=models.CharField(default=1, help_text='Enter a 6-digit PIN code', max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_pin', message='PIN must be exactly 6 digits', regex='^\\d{6}$')]),
            preserve_default=False,
        ),
    ]
