# Generated by Django 6.0 on 2025-12-28 23:28

import django.core.validators
import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_vault_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=docs.models.doc_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'csv', 'ods', 'ppt', 'pptx', 'odp', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp', 'zip', 'rar', '7z', 'tar', 'gz', 'json', 'xml', 'html', 'css', 'js'])]),
        ),
    ]
