# Generated by Django 6.0 on 2026-02-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_document_access_tags_alter_documentversion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='can_be_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='can_be_moved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='can_be_printed',
            field=models.BooleanField(default=True),
        ),
    ]
