# Generated by Django 6.0.2 on 2026-02-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_document_can_be_deleted_document_can_be_moved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
    ]
